// Generated by LiveScript 1.3.1
(function(){
  var _, Backbone, Marionette, Rivets, BaseCompositeView;
  _ = require('lodash');
  Backbone = require('backbone');
  Marionette = require('backbone.marionette');
  Rivets = require('rivets');
  BaseCompositeView = (function(superclass){
    var prototype = extend$((import$(BaseCompositeView, superclass).displayName = 'BaseCompositeView', BaseCompositeView), superclass).prototype, constructor = BaseCompositeView;
    prototype.initialize = function(){
      if (!this.viewModel) {
        this.viewModel = new Backbone.Model();
      }
    };
    prototype.onRenderTemplate = function(){
      this.binding = Rivets.bind(this.el, _.result(this, 'bindingContext'));
    };
    prototype.onClose = function(){
      var ref$;
      if ((ref$ = this.binding) != null) {
        ref$.unbind();
      }
    };
    prototype.bindingContext = function(){
      return {
        collection: this.collection,
        model: this.model,
        view: this,
        viewModel: this.viewModel
      };
    };
    function BaseCompositeView(){
      this.bindingContext = bind$(this, 'bindingContext', prototype);
      this.onClose = bind$(this, 'onClose', prototype);
      this.onRenderTemplate = bind$(this, 'onRenderTemplate', prototype);
      BaseCompositeView.superclass.apply(this, arguments);
    }
    return BaseCompositeView;
  }(Marionette.CompositeView));
  module.exports = BaseCompositeView;
  function bind$(obj, key, target){
    return function(){ return (target || obj)[key].apply(obj, arguments) };
  }
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
