// Generated by LiveScript 1.3.1
(function(){
  var _, Backbone, Marionette, Rivets, BaseCollectionView;
  _ = require('lodash');
  Backbone = require('backbone');
  Marionette = require('backbone.marionette');
  Rivets = require('rivets');
  BaseCollectionView = (function(superclass){
    var prototype = extend$((import$(BaseCollectionView, superclass).displayName = 'BaseCollectionView', BaseCollectionView), superclass).prototype, constructor = BaseCollectionView;
    prototype.initialize = function(options){
      if (!this.viewModel) {
        this.viewModel = new Backbone.Model();
      }
    };
    prototype.onBeforeRender = function(){
      this.binding = Rivets.bind(this.el, _.result(this, 'bindingContext'));
    };
    prototype.onClose = function(){
      var ref$;
      if ((ref$ = this.binding) != null) {
        ref$.unbind();
      }
    };
    prototype.bindingContext = function(){
      return {
        view: this,
        viewModel: this.viewModel
      };
    };
    function BaseCollectionView(){
      this.bindingContext = bind$(this, 'bindingContext', prototype);
      this.onClose = bind$(this, 'onClose', prototype);
      this.onBeforeRender = bind$(this, 'onBeforeRender', prototype);
      this.initialize = bind$(this, 'initialize', prototype);
      BaseCollectionView.superclass.apply(this, arguments);
    }
    return BaseCollectionView;
  }(Marionette.CollectionView));
  module.exports = BaseCollectionView;
  function bind$(obj, key, target){
    return function(){ return (target || obj)[key].apply(obj, arguments) };
  }
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
