// Generated by LiveScript 1.3.1
(function(){
  var Rivets;
  Rivets = require('rivets');
  module.exports = function(){
    Rivets.configure({
      handler: function(context, ev, binding){
        this.call(binding.model, context, ev, binding);
      }
    });
  };
}).call(this);
