// Generated by LiveScript 1.3.1
(function(){
  var Rivets;
  Rivets = require('rivets');
  module.exports = function(){
    Rivets.formatters['!'] = function(x){
      return !x;
    };
  };
}).call(this);
