// Generated by LiveScript 1.3.1
(function(){
  var _, Backbone, Marionette;
  _ = require('lodash');
  Backbone = require('backbone');
  Marionette = require('backbone.marionette');
  module.exports = function(){
    Marionette.Application.prototype._initChannel = function(){
      this.channelName = _.result(this, 'channelName') || 'global';
      this.channel = _.result(this, 'channel') || Radio.channel(this.channelName);
    };
  };
}).call(this);
